# config.yaml
api_keys:
  virustotal:

engines:
  google: true
  bing: true
  virustotal: true
  yahoo: true
  ask: true
  baidu: true
  netcraft: false
  dnsdumpster: false
  threatcrowd: false
  crtsearch: true
  passivedns: false

threads: 30
timeout: 25
verbose: false
output_file: results.txt